version: "3.8"
services:
  patient:
    image: 'patient:v1'
    container_name: patient
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mediscreen_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  history:
    image: 'history:v1'
    container_name: history
    ports:
      - "8082:8082"
    restart: on-failure
    environment: 
      - SPRING_DATA_MONGODB_DATABASE=PatientHistory
      - SPRING_DATA_MONGODB_HOST=mongodb

  assesmment:
    image: 'assessment:v1'
    container_name: assessment
    ports:
      - "8080:8080"
    restart: on-failure

  mysql:
    image: 'mysql'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=mediscreen_db
    ports:
      - "3307:3306"

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27018"
    environment:
    - PUID=1000
    - PGID=1000
    # - MONGO_INITDB_ROOT_USERNAME=rootuser
    # - MONGO_INITDB_ROOT_PASSWORD=rootpass

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
        - '8077:80'
    environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - PMA_ARBITRARY=1

  frontend:
    image: 'frontend:v1'
    container_name: frontend
    ports:
      - "8090:8090"